import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    nameFr: "Pare-chocs avant - Golf 7",
    nameAr: "مصد أمامي - جولف 7",
    descriptionFr: "Pare-chocs avant de haute qualité pour Volkswagen Golf 7. Compatible avec les modèles 2013-2020. Finition OEM.",
    descriptionAr: "مصد أمامي عالي الجودة لفولكس واجن جولف 7. متوافق مع موديلات 2013-2020. تشطيب OEM.",
    oldPrice: 45000,
    newPrice: 38000,
    image: "/car-front-bumper-black-auto-part.jpg",
    images: ["/car-front-bumper-black-auto-part.jpg"],
    category: "carrosserie",
    brand: "Volkswagen",
    model: "Golf 7",
    year: "2013-2020",
    stock: 5,
    sku: "VW-G7-BMP-001",
  },
  {
    id: "2",
    nameFr: "Phare LED - Peugeot 208",
    nameAr: "مصباح LED - بيجو 208",
    descriptionFr: "Phare avant LED haute performance pour Peugeot 208. Éclairage puissant et durable. Installation facile.",
    descriptionAr: "مصباح أمامي LED عالي الأداء لبيجو 208. إضاءة قوية ومتينة. تركيب سهل.",
    oldPrice: 32000,
    newPrice: 27500,
    image: "/car-led-headlight-modern-auto-optics.jpg",
    images: ["/car-led-headlight-modern-auto-optics.jpg"],
    category: "optique",
    brand: "Peugeot",
    model: "208",
    year: "2019-2024",
    stock: 8,
    sku: "PG-208-LED-001",
  },
  {
    id: "3",
    nameFr: "Rétroviseur droit - Clio 4",
    nameAr: "مرآة يمنى - كليو 4",
    descriptionFr: "Rétroviseur extérieur droit pour Renault Clio 4. Avec système de réglage électrique. Couleur noire.",
    descriptionAr: "مرآة خارجية يمنى لرينو كليو 4. مع نظام تعديل كهربائي. اللون أسود.",
    oldPrice: 18000,
    newPrice: 15000,
    image: "/car-side-mirror-black-auto-part.jpg",
    images: ["/car-side-mirror-black-auto-part.jpg"],
    category: "carrosserie",
    brand: "Renault",
    model: "Clio 4",
    year: "2012-2019",
    stock: 12,
    sku: "RN-CL4-MIR-R01",
  },
  {
    id: "4",
    nameFr: "Feux arrière - Dacia Duster",
    nameAr: "مصابيح خلفية - داسيا داستر",
    descriptionFr: "Feux arrière complets pour Dacia Duster. Design moderne LED. Ensemble gauche et droit.",
    descriptionAr: "مصابيح خلفية كاملة لداسيا داستر. تصميم LED عصري. طقم يمين ويسار.",
    oldPrice: 22000,
    newPrice: 18500,
    image: "/car-tail-light-rear-lamp-auto.jpg",
    images: ["/car-tail-light-rear-lamp-auto.jpg"],
    category: "optique",
    brand: "Dacia",
    model: "Duster",
    year: "2018-2024",
    stock: 6,
    sku: "DC-DST-TL-001",
  },
  {
    id: "5",
    nameFr: "Capot avant - Hyundai i10",
    nameAr: "غطاء أمامي - هيونداي i10",
    descriptionFr: "Capot avant en acier galvanisé pour Hyundai i10. Résistant à la corrosion. Prêt à peindre.",
    descriptionAr: "غطاء أمامي من الفولاذ المجلفن لهيونداي i10. مقاوم للتآكل. جاهز للطلاء.",
    oldPrice: 55000,
    newPrice: 48000,
    image: "/car-hood-bonnet-silver-auto-body.jpg",
    images: ["/car-hood-bonnet-silver-auto-body.jpg"],
    category: "carrosserie",
    brand: "Hyundai",
    model: "i10",
    year: "2014-2020",
    stock: 3,
    sku: "HY-I10-HOD-001",
  },
  {
    id: "6",
    nameFr: "Clignotant latéral - Symbol",
    nameAr: "إشارة جانبية - سيمبول",
    descriptionFr: "Clignotant répétiteur latéral pour Renault Symbol. LED orange. Installation sans modification.",
    descriptionAr: "إشارة جانبية لرينو سيمبول. LED برتقالي. تركيب بدون تعديل.",
    oldPrice: 8000,
    newPrice: 6500,
    image: "/car-side-indicator-turn-signal-light.jpg",
    images: ["/car-side-indicator-turn-signal-light.jpg"],
    category: "optique",
    brand: "Renault",
    model: "Symbol",
    year: "2008-2018",
    stock: 20,
    sku: "RN-SYM-IND-001",
  },
  {
    id: "7",
    nameFr: "Aile avant gauche - Polo 6",
    nameAr: "جناح أمامي أيسر - بولو 6",
    descriptionFr: "Aile avant gauche pour Volkswagen Polo 6. Acier de haute qualité. Compatible OEM.",
    descriptionAr: "جناح أمامي أيسر لفولكس واجن بولو 6. فولاذ عالي الجودة. متوافق OEM.",
    oldPrice: 35000,
    newPrice: 29000,
    image: "/car-body-parts-bumper-fender.jpg",
    images: ["/car-body-parts-bumper-fender.jpg"],
    category: "carrosserie",
    brand: "Volkswagen",
    model: "Polo 6",
    year: "2017-2024",
    stock: 4,
    sku: "VW-PL6-FND-L01",
  },
  {
    id: "8",
    nameFr: "Phare antibrouillard - Seat Ibiza",
    nameAr: "مصباح ضبابي - سيات إيبيزا",
    descriptionFr: "Phare antibrouillard avant pour Seat Ibiza. Verre résistant aux chocs. Ampoule H11 incluse.",
    descriptionAr: "مصباح ضبابي أمامي لسيات إيبيزا. زجاج مقاوم للصدمات. لمبة H11 مضمنة.",
    oldPrice: 12000,
    newPrice: 9500,
    image: "/car-headlights-tail-lights-automotive-optics.jpg",
    images: ["/car-headlights-tail-lights-automotive-optics.jpg"],
    category: "optique",
    brand: "Seat",
    model: "Ibiza",
    year: "2015-2022",
    stock: 10,
    sku: "ST-IBZ-FOG-001",
  },
]

export const wilayas = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra",
  "Béchar", "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret",
  "Tizi Ouzou", "Alger", "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda",
  "Sidi Bel Abbès", "Annaba", "Guelma", "Constantine", "Médéa", "Mostaganem",
  "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", "Illizi", "Bordj Bou Arréridj",
  "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", "Khenchela",
  "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
  "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal",
  "Béni Abbès", "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Meniaa"
]

export const brands = ["Volkswagen", "Peugeot", "Renault", "Dacia", "Hyundai", "Seat"]
export const years = ["2008-2018", "2012-2019", "2013-2020", "2014-2020", "2015-2022", "2017-2024", "2018-2024", "2019-2024"]
